version: "3"

services:
  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRES_USER=${POSTGRESQL_USER}
      - POSTGRES_DB=${POSTGRESQL_DATABASE}
    networks:
      - symfony_app
  php:
    build:
      context: ./php
      args:
        TIMEZONE: ${TIMEZONE}
    command: [ "bash", "-c", "chown -R www-data:www-data /var/www/symfony/var && php-fpm" ]
    volumes:
      - ../${APP_FOLDER}:/var/www/symfony:cached
      - symfony_app_var:/var/www/symfony/var
      - symfony_app_vendor:/var/www/symfony/vendor
    networks:
      - symfony_app
  nginx:
    build:
      context: ./nginx
    volumes:
      - ../${APP_FOLDER}:/var/www/symfony:cached
      - symfony_app_var:/var/www/symfony/var
      - symfony_app_vendor:/var/www/symfony/vendor
      - ./certs:/etc/nginx/certs
    ports:
      - "443:443"
    networks:
      - symfony_app
    env_file:
      - .env.nginx.local

volumes:
  symfony_app_var:
  symfony_app_vendor:
  db_data:

networks:
  symfony_app:
