version: '3'
services:
  spa-nginx:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/ssl/private
      - ../${APP_DIR}/dist:/var/www/html/spa
      - ../../m-ssr/${APP_DIR}/dist:/var/www/html/ssg
    network_mode: host